name: Lint and Test Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Set up Python 3.12
      run: uv python install 3.12
    - name: Install dependencies
      run: |
        uv sync
        source .venv/bin/activate
    - name: Lint with flake8
      run: |
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv
    - name: Sort imports with isort
      run: |
        uv run isort . --check-only --diff --skip .venv --line-length 120
    - name: Format with black
      run: |
        uv run black . --check --diff --exclude=.venv -l 120
    - name: Test with nox
      run: |
        uv run nox
